/*
 * This Java source file was generated by the Gradle 'init' task.
 * Author: Jefferson Klamas Marzani (jkm)
 * Aplicaçao para gerenciamento de projetos e tarefas.
 */
package main;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Date;
import java.util.List;
import model.Task;

public class Main {
//    public String getGreeting() {
//        return "Hello World!";
//    }

    public static void main(String[] args) {
        
//  Esta apenas cria um novo projeto no banco      
//        ProjectController projectController = new ProjectController();
//     
//        Project project = new Project();
//        project.setName("Projeto Teste");
//        project.setDescription("Descriçao do teste");
//        projectController.save(project);

// Esta altera as informaçoes indicadas no banco
//        ProjectController projectController = new ProjectController();
//
//        Project project = new Project();
//        project.setId(2);
//        project.setName("Projeto II");
//        project.setDescription("Teste II");
//        projectController.update(project);
//        
//        List<Project> projects = projectController.getAll();
//        System.out.println("Total de Projetos = " + projects.size());

//           ProjectController projectController = new ProjectController();
//
//            projectController.removeById(Numero ID);
            
//        TaskController taskController = new TaskController();
//
//        Task task = new Task();
//        task.setIdProject(2);
//        task.setName("Criar as telas da aplicaçao!!");
//        task.setDescription("Devem ser criados telas para que os cadastros possam ser realziados");
//        task.setNotes("Inicio deve ser ja nesta semana de 04/25/2022 a 04/29/2022");
//        task.setIsCompleted(false);
//        task.setDeadline(new Date());
//
//
//        taskController.save(task);
//
//        task.setName("Alterar telas de Aplicaçao.");
//        taskController.update(task);
//        List<Task> tasks = taskController.getAll(1);
//        System.out.println("Total de Tarefas = " + tasks.size());
    }
}
